[application]
name = "Esprit Seeder"
default_platform = "desktop"

[web.app]
title = "Esprit Seeder"

[web.resource]
style = ["tailwind.css"]

[web.resource.dev]

[desktop]
enable_default_menu_bar = false

[desktop.window]
width = 500
height = 520
resizable = false
decorations = false
title = "Esprit Seeder"

[desktop.resource]
style = ["tailwind.css"]

[bundle]
identifier = "org.espritdecorpsgaming.espritseeder"
publisher = "Esprit De Corps Gaming"
icon = ["icons/icon.ico", "icons/icon.png"]
resources = ["icons/*"]

[bundle.windows.nsis]
installer_hooks = "installer_hooks.nsh"
