<Project>
  <PropertyGroup>
    <Version>0.2.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Company>Cat Tree Gaming LLC</Company>
    <Product>Fullobby</Product>
    <Copyright>© Cat Tree Gaming L.L.C.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
</Project>
