<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Company>Comp HLL</Company>
    <Product>CHLL Seeding</Product>
    <Copyright>© Comp HLL</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
</Project>
